### ISSUE TITLE
versioning would be nice

### ISSUE THREAD

**Issue by dryaf** [skx/deployr#9]
versioning and rollback would be nice
you might want to take a look at harp

https://github.com/bom-d-van/harp

**Comment by skx** [comment]
I tend to think of versioning as something that must be supported more generally.   For my own (simple) recipes I pretty much do:

* wget ..
* systemctl restart

So I could pretend I support versioning via a `RELEASE` variable which would  let you change the number backwards - but that doesn't work if there are database-migrations involved too.

In short I'm not sure that this is a problem I can fix, in the general case.   I can let _you_ write a script which will deploy version A, Y, or Z, and restart appropriately.  But I can't say "roll-back to previous" since I don't keep state, and I think that should be avoided.

Of course if there are issues you could deploy in the blue/green pattern, and that is supported easily enough..

If you can think of specific actions which could be changed/improved/implemented I'd be happy to hear more though.
